#!/bin/sh

set -e

case "$1" in
  configure|remove|purge|abort-install|abort-upgrade|disappear)
    if command -v glib-compile-schemas >/dev/null 2>&1; then
      glib-compile-schemas /usr/share/glib-2.0/schemas
    fi
    if command -v update-mime-database >/dev/null 2>&1; then
      update-mime-database /usr/share/mime
    fi
    if command -v update-desktop-database >/dev/null 2>&1; then
      update-desktop-database -q /usr/share/applications
    fi
    if command -v gtk-update-icon-cache >/dev/null 2>&1; then
      gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
    elif command -v gtk4-update-icon-cache >/dev/null 2>&1; then
      gtk4-update-icon-cache -q -t -f /usr/share/icons/hicolor
    fi
    ;;
esac
